### ISSUE TITLE
Interesting approach to state management.

### ISSUE THREAD

**Issue by elhe26** [NourEldinShobier/pmvvm#1]
Hi,

This post is to appreciate your efforts in simplifying state management. I'm an avid user of stacked and try to collaborate on the package every time I can. I'll look forward to giving this plugin a go on my next project.

Thanks,

**Comment by NourEldinShobier** [comment]
Hi Elhe, 

I hope you find it useful, and if you have any questions regarding clean patterns, clean architecture, ...etc. , feel free to ask :v:
