### ISSUE TITLE
How to reset the VM reload the whole screen on tap

### ISSUE THREAD

**Issue by shiwam77** [NourEldinShobier/pmvvm#10]
I want to refresh the screen whenever internet gone off then retry popup then have to reload the whole screen but it stuck on loading widget only....but i am doing things by changing the key but don't work.

**Comment by NourEldinShobier** [comment]
Hi @shiwam77 

You need to listen to the network connection stream within the view model and call `notifyListeners()` whenever it changes to refresh the view

Hope this helps you

**Comment by shiwamSliceit** [comment]
Plz show me one example while get back to view from other screen  i want dispose the vm & view & then reload all the screen cause network connectivity  package is not working in flutter module actually that's not the case i just want to dispose the vm & view & reload it again

**Comment by NourEldinShobier** [comment]
Sorry @shiwamSliceit but i can't follow up with what you want

The provider package handles the disposal of the VM by itself, moreover, you can control this behavior through the `disposeVM` parameter of the MVVM widget.

So, can you expand more on what is the scenario you are trying to do from user's perspective

**Comment by NourEldinShobier** [comment]
Im assuming you managed to fix your issue, so I'm going to close it

feel free to open it again if there is any update

**Comment by shiwam77** [comment]
I just want to reload the the whole screen along with vm but it's not working even i am changing the key it's just build the widget again but vm is not..& my screen has to much business logic & clearing whole thing is too much mess & have to write unnecessary code &  have figured out the solution right now i am wrapping the mvvm widget in statefull widget & from that parents content i am changing the key but it's not a recommend way to do things

**Comment by shiwam77** [comment]
static void refreshScreen(BuildContext context) {
    context.findAncestorStateOfType<_ParentWidgetState>().refreshScreenState();
  }




Key key = UniqueKey();

  void refreshScreenState() {
    setState(() {
      key = UniqueKey();
    });
  }

**Comment by NourEldinShobier** [comment]
Dude i really want to help you =D

i feel like it's a small issue so can u please provide a **full code sample** of what you are doing (the VM and View) , this will help me better understand what you want
