### ISSUE TITLE
How is it different from other MVVM architecture?

### ISSUE THREAD

**Issue by saileshbro** [NourEldinShobier/pmvvm#2]
Hey @NourEldinShobier, nice work.
Can you highlight how this package is different from other MVVM packages like [stacked](https://github.com/filledstacks/stacked).
Thanks.

**Comment by NourEldinShobier** [comment]
Hi @saileshbro , actually I did highlight the differences between both of them in the FAQ section.

**Comment by sanalkv** [comment]
I believe the buildcontext should never be accessed inside viewmodel.

**Comment by NourEldinShobier** [comment]
hi @sanalkv , that's a good point... Long story short, I believe each person has different preferences. Being able to access the `buildcontext` from the view model has some advantages like fetching the providers from the VM itself...etc. Basically, it helps you to keep the view clean of any logic that is not related to view itself

That being said, I know that it's a double-edged feature that some developers might abuse, but that doesn't mean it shouldn't exist

Again, I believe each person has different preferences =D
