### ISSUE TITLE
How to use notifylisteners

### ISSUE THREAD

**Issue by ggblake** [NourEldinShobier/pmvvm#4]
How does one implement listeners/consumers? The viewmodel
has the notifylistners method but how do we make widgets in a satelessview
respond to the norification?

**Comment by NourEldinShobier** [comment]
hi, @ggblake, there are 3 ways to listen to a `viewmodel` changes after declaring the `MVVM` widget:
- using a `statelessview` widget, which listens by default to the `viewmodel` you specify:
- using a `consumer/selecter` + specifying the `viewmodel` you specify
- using `context.fetch<MyViewModel>(listen: true/false)` in your `stateful/stateless` widget
