### ISSUE TITLE
Multiple viewmodels

### ISSUE THREAD

**Issue by ggblake** [NourEldinShobier/pmvvm#5]
Can a page widget have references to more than one view model

**Comment by NourEldinShobier** [comment]
Can you elaborate more?

**Comment by ggblake** [comment]
I have several viewmodels and some pages need to reference more than one vm
so something like:
  @override
  Widget build(BuildContext context) {
    return MVVM(
      view: (context, vm1) => EmailListView(),
      viewModel: EmailsVM (),
    );
    return MVVM(
      view: (context, vm2) => ClientListView(),
      viewModel: ClientLisVM (),
    );
  }
}
